name: Healthcheck

on:
  schedule:
    - cron: '12 * * * *'

jobs:
  ping_the_app:
    runs-on: ubuntu-20.04
    steps:
      - name: Pokedex healthcheck
        uses: jtalk/url-health-check-action@v4
        with:
          url: https://full-stack-open-pokedex-qf6e.onrender.com/health
          max-attempts: 3
          retry-delay: 5s
          retry-all: true
      - name: Send slack notification
        id: slack
        uses: slackapi/slack-github-action@v1.25.0
        with:
          payload: |
            {
                "blocks": [
                  {
                    "type": "header",
                    "text": {
                      "type": "plain_text",
                      "text": "Healthcheck result: ${{ job.status }}",
                      "emoji": true
                    }
                  },
                  {
                    "type": "section",
                    "text": {
                      "type": "mrkdwn",
                      "text": "Job: `ping_the_app`"
                    },
                    "accessory": {
                      "type": "button",
                      "text": {
                        "type": "plain_text",
                        "text": "Go to logs",
                        "emoji": true
                      },
                      "value": "click_me_123",
                      "url": "https://dashboard.render.com/web/srv-cncggmed3nmc738gbekg/logs",
                      "action_id": "button-action"
                    }
                  }
                ]
            }
        env:
            SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
            SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOk